export { default as Navbar } from './Navbar/navbar'
export { default as EachProject } from './Each Project/eachproject'
export { default as Language } from './languages/languages'
export { default as Skills } from './skills/skills'
export { default as Stacks } from './Stacks/stack'
export { default as ResponsiveBadge } from './ResponsiveBadge/responsive'
export { default as Technology } from './Technology/technology'
export { default as Footer } from './Footer/footer'
export { default as SocialMedia } from './Social Media/socialMedia'
export { default as GitHub } from './GitHub/github'
export { default as LoadingPage } from './LoadingPage/loading'